trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: agrotech-variables

steps:
  - script: |
      docker compose -f docker-compose.prod.yml config
      docker compose -f docker-compose.prod.yml up --build -d
    displayName: Subir via docker compose
    env:
      DATABASE_URL: $(DATABASE_URL)
      DATABASE_USERNAME: $(DATABASE_USERNAME)
      DATABASE_PASSWORD: $(DATABASE_PASSWORD)
      DB_POOL_SIZE: $(DB_POOL_SIZE)
      DDL_AUTO: $(DDL_AUTO)
      SHOW_SQL: $(SHOW_SQL)
      LOG_SQL: $(LOG_SQL)
      RABBITMQ_HOST: $(RABBITMQ_HOST)
      RABBITMQ_PORT: $(RABBITMQ_PORT)
      RABBITMQ_USERNAME: $(RABBITMQ_USERNAME)
      RABBITMQ_PASSWORD: $(RABBITMQ_PASSWORD)
      RABBITMQ_VHOST: $(RABBITMQ_VHOST)
      SENSOR_API_URL: $(SENSOR_API_URL)
      JWT_SECRET: $(JWT_SECRET)
      SENSOR_WEBHOOK_API_KEY: $(SENSOR_WEBHOOK_API_KEY)