CREATE TABLE harvests (
    id UUID PRIMARY KEY,
    harverst_season VARCHAR(255),
    crop VARCHAR(255) NOT NULL,
    planting_date DATE NOT NULL,
    expected_harvest_date DATE,
    actual_start_date DATE,
    actual_end_date DATE,
    planted_area NUMERIC(10, 2),
    harvested_area NUMERIC(10, 2),
    expected_yield NUMERIC(10, 2),
    actual_yield NUMERIC(10, 2),
    yield_per_hectare NUMERIC(8,  2),
    quality_grade VARCHAR(20),
    market_price_per_ton NUMERIC(10, 2),
    total_revenue NUMERIC(12, 2),
    production_cost NUMERIC(12, 2),
    profit_margin NUMERIC(12, 2),
    harvest_notes VARCHAR(1000),
    weather_conditions VARCHAR(500),
    status VARCHAR(20) DEFAULT 'PLANNED',
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    field_id UUID NOT NULL,
    CONSTRAINT fk_harvest_field FOREIGN KEY (field_id) REFERENCES fields (id)
);